cc_binary(
    name = "basic_lighting_in_view_space",
    srcs = glob([
        "*.cpp",
        "*.hpp",
        "*.h",
    ]),
    data = glob(["*.png"]),
    deps = [
        "//gl",
        "//glew",
        "//glfw",
        "//glm",
    ],
)
