cc_binary(
    name = "texture",
    srcs = glob([
        "*.cpp",
        "*.hpp",
        "*.h",
    ]),
    data = glob(["*.jpg"]),
    deps = [
        "//gl",
        "//glew",
        "//glfw",
    ],
)
