
cc_binary(
    name = "scene",
    srcs = ["main.cpp",
            "Scene.cpp",
            "Scene.hpp",
            "Window.cpp",
            "Window.hpp"
    ],
    deps = [
        "//gl",
        "//glfw",
        "//glew",
        "//glm",
    ],
)
